service: serverless-name-generator

package:
  exclude:
    - ./**
  include:
    - node_modules/
    - index.js
    - src/handler.js

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 4
  versionFunctions: false # optional, default is true

plugins:
  - serverless-offline

functions:
  generate:
    handler: src/handler.handler # required, handler set in AWS Lambda
    description: Generates unique and memorable names # optional, Description to publish to AWS
    events:
      - http:
          path: generate
          method: get
          cors: true
